spring:
  application:
    name: proposal-mcp-service
#  ai:
#    mcp:
#      server:
#        sse-endpoint: /${spring.application.name}/sse

server:
  port: 8082
  shutdown: immediate
#  servlet:
#    context-path: /${spring.application.name}

logging:
  level:
    com.example: debug
    org.springframework.ai: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
