spring:
  application:
    name: proposal-mcp-service
#  ai:
#    mcp:
#      server:
#        sse-endpoint: /${spring.application.name}/sse

server:
  port: 18082
  shutdown: immediate

logging:
  level:
    com.example: debug
    org.springframework.ai: debug
