spring:
  ai:
    ollama:
      init:
        pull-model-strategy: when_missing
        timeout: 15m
        max-retries: 2

      chat:
        options:
          # model: gpt-oss:20b
          model: llama3.2:3b

      embedding:
        options:
          model: nomic-embed-text

    model:
      chat: ollama
      embedding: ollama

    vectorstore:
      pgvector:
        dimensions: 768
        table-name: vector_store_small
