spring:
  ai:
    azure:
      openai:
        api-key: ${AZURE_OPENAI_API_KEY}
        endpoint: ${AZURE_OPENAI_ENDPOINT}
        chat:
          options:
            deployment-name: ${AZURE_OPENAI_CHAT_DEPLOYMENT_NAME:gpt-4o}
            temperature: 0.7

        embedding:
          options:
            deployment-name: ${AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME:text-embedding-3-small}

    vectorstore:
      pgvector:
        dimensions: 1536
        table-name: vector_store_large
